In [2]:
# 책 4챕터부터 보면 됩니다여

In [3]:
import numpy as np  # numpy 모듈을 불러올거고 앞으로 np라고 부를게
my_list = list(range(1000000))
my_array = np.arange(1000000)

In [4]:
# %timeit 얼마나 걸리는지 확인
%timeit my_list2 = [i * 2 for i in my_list] #리스트 컴프리헨션 / 리스트 안에 있는 숫자에 모두 x2를 하겠다
%timeit my_array2 = my_array * 2

63.6 ms ± 997 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.46 ms ± 36.4 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
# 파이썬에서 사용했던 list를 array 함수에 집어넣으면 numpy에서 사용할 수 있는 데이터 형태로 변경해줌
a = [
    [1, 1.2, 3],
    [-123, 123, 0]
]
print(type(a))
data = np.array(a)
print(data)
print(type(data))

# 각각 아이템으로 곱셈을 해줌

<class 'list'>
[[   1.     1.2    3. ]
 [-123.   123.     0. ]]
<class 'numpy.ndarray'>


In [12]:
# 0차원 : 스칼라(scala) = 그룹이 아닌 단일데이터, 1차원: 벡터(vector),
# 2차원: 행렬(matrix), 3차원 이상: 텐서(tenset)
print(data * 10)
print(data + data)

[[   10.    12.    30.]
 [-1230.  1230.     0.]]
[[   2.     2.4    6. ]
 [-246.   246.     0. ]]


In [16]:
print(data.shape)  # 가장 큰 배열부터의 데이터 모양
# (데이터 안에 2개의 리스트와 3개의 값이 있다.)
print(data.dtype)  # float 타입인데 64개의 칸을 이용한다라는 뜻..(2의 64제곱)

(2, 3)
float64


# ndarray 생성하기
    - n차원의 배열
    - list는 가변성이 있고, array는 고정값에 좀 더 가까움

In [7]:
data1 = [1, 2, 3, 4, 5]
arr1 = np.array(data1)
print(arr1)
print(type(arr1)) # numpy 안에 있는 ndarray 입니당

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
arr2 = np.array([[1.1, 2.2], [3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [9]:
print(arr1.ndim)  # 배열의 차원수를 보여줌 (1차원, 2차원)
print(arr2.ndim) 

1
2


In [11]:
print(arr1.shape)
# 원소 5개를 가진 1차원 배열이라는 뜻
# (5, ) <- 빈 값은 1차원 배열
print(arr2.shape)
# 2행 2열 구조

(5,)
(2, 2)


In [12]:
# print([0] * 10)
print(np.zeros(10))  # 0으로 가득채워진 상자를 만들거야(데이터를 채울 배열 만들기)
print(np.zeros(  (5, 5)  ))  # 5x5 형태로 만들어줌
print(np.empty(  (2, 2, 2)  )) # 0도 의미가 있는 데이터가 되는 경우 empty 이용하는 것이 더 좋음

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[ 4.67296746e-307  1.69121096e-306]
  [-4.67218654e+043  1.42419938e-306]]

 [[ 7.56603881e-307  8.45603440e-307]
  [ 4.45046008e-307  2.37667058e-312]]]


In [30]:
print(np.arange(10))  # 0부터 9까지 있는 순서있는 배열 생성

[0 1 2 3 4 5 6 7 8 9]


## nparray 자료형

In [44]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

print(arr1.dtype)
print(arr2.dtype)

int64
int64


In [45]:
# 아래와 같은 
arr1 = np.array([1, 2, 3], dtype=np.float64) # 실수로 바꿔줘
arr2 = np.array([1, 2, 3], dtype=np.int32) # 정수로 바꿔줘
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [50]:
arr1 = np.array([1, 2, 3])
print(arr1.dtype)
float_arr1 = arr1.astype(np.float64)
print(float_arr1)
print(float_arr1.dtype)
# astype 바꾸고 싶은 타입으로 변경해주는 함수

int64
[1. 2. 3.]
float64


In [51]:
arr2 = np.array([1.1, 2.2, 3.3, 9.9]) # 실수를 정수로 강제로 형변환 하는 경우 뒷자리는 버림처리됨
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64)
print(int_arr2)
print(int_arr2.dtype)

float64
[1 2 3 9]
int64


# 산술연산

In [72]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [71]:
print(arr * arr)  # 같은 위치에 있는 값끼리 곱해줌

[[ 1  4  9]
 [16 25 36]]


In [73]:
print(arr + arr)
print(1 / arr) # 1/1, 1/2, 1/3...
print(arr ** 3)

[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [74]:
arr2 = np.array([[3, 2, 1], [1, 2, 3]])
print(arr)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]


In [75]:
print(arr > arr2) 
# 각각의 위치를 비교하여 True/False 출력

[[False False  True]
 [ True  True  True]]


In [77]:
print(arr == 3)

[[False False  True]
 [False False False]]


## 색인과 슬라이싱

In [80]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [86]:
arr[7] # 데이터로 접근한다면 인덱스로 접근

np.int64(7)

In [87]:
print(arr[7])

7


In [88]:
print(arr[2:5]) # 2번째 데이터부터 4번째 데이터까지

[2 3 4]


In [92]:
arr[2:5] = 10
print(arr)
# 2번째부터 4번째까지 지정한 값(10)이 모두 들어감
# 잘라진 데이터를 바꿨는데 원본이 바뀜

[ 0  1 10 10 10  5  6  7  8  9]


In [100]:
py_list = [1, 2, 3, 4, 5]
py_list[2:3].pop()
print(py_list)
# 파이썬 문법으로는 슬라이싱 하면 카피가 됨 (원본은 건드리지 X)

[1, 2, 3, 4, 5]


In [106]:
arr = np.array([[1, 2, 3,], [4, 5, 6]])
print(array)

[[1 2 3]
 [4 5 6]]


In [110]:
print(arr[1][1]) # 리스트인 경우 각 인덱스를 [][]로 묶어주었지만
print(arr[1, 1]) # 넘파이에서는 쉼표로 묶어 색인 가능

5
5


In [111]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
          [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
          [[11, 22, 33], [44, 55, 66], [77, 88, 99]]])

In [116]:
print(arr3d[1][1][2])

16


In [122]:
arr3d[:1, 1:, 2:] # 슬라이싱은 차원을 유지, 인덱스접근하면 차원으로 들어가므로 줄어듦

array([[[6],
        [9]]])

In [123]:
arr3d[0, 1:, 2:] = 9999
print(arr3d)

[[[   1    2    3]
  [   4    5 9999]
  [   7    8 9999]]

 [[  11   12   13]
  [  14   15   16]
  [  17   18   19]]

 [[  11   22   33]
  [  44   55   66]
  [  77   88   99]]]


# 불리언 값으로 선택

In [130]:
names = np.array(['hong', 'kim', 'hong', 'kim'])
data = np.array([['math', 60], ['math', 90], ['eng', 70], ['eng', 50]])

In [132]:
# 먼저 불리언 데이터를 만들어줌

names == 'hong'

array([ True, False,  True, False])

In [136]:

# data[[True, False, True, False]]
data[names == 'hong']
# 특정 조건에 맞는 데이터를 고를 때 사용
# 위의 'hong' 값(T, F, T, F) 위치에 맞게 값을 뽑아줌

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [135]:
print(data[names == 'hong', 1]) # 인덱싱
print(data[names == 'hong', :1]) # 슬라이싱

['60' '70']
[['math']
 ['eng']]


In [137]:
names != 'hong' # hong이 아닌가요?

array([False,  True, False,  True])

In [139]:
print(~(names == 'hong')) # (names == 'hong') 의 값을 반전한 값
# names == 'hong' 이름이 hong인가요?
# 앞에 ~가 붙으므로서 이름이 hong이 아닌가요?로 반전됨

[False  True False  True]


In [141]:
cond = names == 'kim'  # 변수를 먼저 넣어주고
data[cond] # 결과값을 넣어주면

array([['math', '90'],
       ['eng', '50']], dtype='<U21')

## 팬시 색인(fancy indexing)

In [14]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i  # 한 줄 전체에 i를 넣어줘
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [15]:
arr[[4, 3, 0, 5]]
# 인덱싱으로 직접적으로 골라서 가져오는 것
# 내가 지정한 순서대로 출력됨

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [16]:
arr[[-3, -5, -1]] #뒤에서부터 골라 가져옴

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [22]:
arr = np.arange(32).reshape(8, 4) # 가지고 있는 0, 31 배열을 다음과 같이(8,4)로 바꾸겠다
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [23]:
arr[[1, 5], [2, 3]]
# 1행의 두번째 데이터
# 5행의 세번째 데이터
# 위치값만 가져옴 (1차원으로 변함)

array([ 6, 23])

In [201]:
arr[[1, 5]][:, [2, 3]]
# 1행과 5행을 먼저 선택
# 그 후 2열과 3열 가져옴 (2차원 배열 유지)

array([[ 6,  7],
       [22, 23]])

## 배열 전치

In [182]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [185]:
print(arr.T)  # 축이 바뀜, 행렬의 곱셈이 가능함

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [189]:
arr * 3   # 가지고 있는 하나하나의 요소를 모두 곱해줌

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42]])

In [193]:
print(arr @ arr.T)   # 행렬의 내적, 곱
print(np.dot(arr, arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


## numpy 함수

In [11]:
import numpy as np

In [14]:
samples = np.random.standard_normal(size=(3, 3))
# 정규분포에서 난수를 생성하는 함수
print(samples)

[[-0.05794162 -0.48959288  0.12334417]
 [ 1.71539554  2.40004598  0.10192348]
 [ 0.49965578  0.65470106 -0.53750776]]


In [17]:
arr1 = np.sqrt(samples)
# samples에 루트를 씌우는 함수
# nan = 숫자가 아닙니다. (데이터가 없습니다)
# 음수는 루트를 씌울 수 없음 => nan (결측치)

print(arr1)

[[       nan        nan 0.35120389]
 [1.3097311  1.54920818 0.31925458]
 [0.70686334 0.809136          nan]]


C:\Users\유승준\AppData\Local\Temp\ipykernel_48116\3391402283.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples)


In [19]:
arr2 = np.abs(samples) # 절대값을 취한다 = 음수를 양수로 바꾸어줌, 절대값으로 바꿔줌
print(arr2)

[[0.05794162 0.48959288 0.12334417]
 [1.71539554 2.40004598 0.10192348]
 [0.49965578 0.65470106 0.53750776]]


In [21]:
np.isnan(arr1)
# 현재 내가 가지고 있는 배열에 nan이 있나요?
# 위치에 nan이 있으면 T, 없으면 F

array([[ True,  True, False],
       [False, False, False],
       [False, False,  True]])